mysqldb:
    container_name: mysqldb
    image: tutum/mysql
    restart: always
    ports:
        - "3306:3306"
    environment:
        - MYSQL_USER=airflow
        - MYSQL_PASS=airflow
        - ON_CREATE_DB=airflow

rabbitmq:
    container_name: rabbitmq
    image: puckel/docker-rabbitmq
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_USER=airflow
        - RABBITMQ_PASSWORD=airflow
        - RABBITMQ_VHOST=airflow

webserver:
    container_name: webserver
    image: puckel/docker-airflow
    restart: always
    # volumes:
    #     - /localpath/to/dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8080:8080"
    links:
        - mysqldb:mysqldb
        - rabbitmq:rabbitmq
        - worker:worker
    command: webserver

flower:
    container_name: flower
    image: puckel/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "5555:5555"
    links:
        - rabbitmq:rabbitmq
    command: flower

worker:
    container_name: worker
    image: puckel/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8793:8793"
    links:
        - mysqldb:mysqldb
        - rabbitmq:rabbitmq
    command: worker

scheduler:
    container_name: scheduler
    image: puckel/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - mysqldb:mysqldb
        - rabbitmq:rabbitmq
    command: scheduler
