mariadb:
    image: mariadb:10
    restart: always
    ports:
        - "3306:3306"
    environment:
        - MYSQL_USER=airflow
        - MYSQL_PASSWORD=airflow
        - MYSQL_DATABASE=airflow
        - MYSQL_ROOT_PASSWORD=wootwoot

rabbitmq:
    image: puckel/docker-rabbitmq
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_USER=airflow
        - RABBITMQ_PASSWORD=airflow
        - RABBITMQ_VHOST=airflow

webserver:
    image: puckel/docker-airflow
    restart: always
    ports:
        - "8080:8080"
    links:
        - mariadb:mariadb
        - rabbitmq:rabbitmq
    command: webserver

flower:
    image: puckel/docker-airflow
    restart: always
    ports:
        - "5555:5555"
    links:
        - rabbitmq:rabbitmq
    command: flower

worker:
    image: puckel/docker-airflow
    restart: always
    links:
        - mariadb:mariadb
        - rabbitmq:rabbitmq
    command: worker
