version: '2'
services:
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=airflow
            - RABBITMQ_DEFAULT_PASS=airflow
            - RABBITMQ_DEFAULT_VHOST=airflow

    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.7.1.3-2
        restart: always
        depends_on:
            - postgres
            - rabbitmq
        environment:
            # - LOAD_EX=n
            - EXECUTOR=Celery
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: puckel/docker-airflow:1.7.1.3-2
        restart: always
        depends_on:
            - rabbitmq
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.7.1.3-2
        restart: always
        depends_on:
            - webserver
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            # - LOAD_EX=n
            - EXECUTOR=Celery
        command: scheduler -n 5

    worker:
        image: puckel/docker-airflow:1.7.1.3-2
        restart: always
        depends_on:
            - scheduler
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - EXECUTOR=Celery
        command: worker
