version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=airflow
            - RABBITMQ_DEFAULT_PASS=airflow
            - RABBITMQ_DEFAULT_VHOST=airflow

    webserver:
        image: puckel/docker-airflow:1.7.1.3
        restart: always
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: puckel/docker-airflow:1.7.1.3
        restart: always
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.7.1.3
        restart: always
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        command: scheduler -n 5

    worker:
        image: puckel/docker-airflow:1.7.1.3
        restart: always
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        command: worker
