version: 2

jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/CircleCI/docker-airflow
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -t puckel/docker-airflow .

  test:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - setup_remote_docker
      - run: |
          docker run puckel/docker-airflow version |grep '1.10.1'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
